services:
  api:
    container_name: Kyquanviet API
    image: ellyx13/projects:kyquanviet-api
    restart: always
    command: uvicorn main:app --reload --workers 2 --host 0.0.0.0 --port 8005
    volumes:
      - ./logs/:/opt/projects/app/logs
    ports:
      - "8011:8005"
    env_file:
      - ./.env/prod.env
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -f http://localhost:8005/v1/health/ping || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 3
    depends_on:
      - db

  db:
    container_name: Kyquanviet Database
    image: mongo
    restart: always
    volumes:
      - ./database:/data/db
    command: --quiet
    ports:
      - 27021:27017
    env_file:
      - ./.env/db.prod.env
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_USERNAME --quiet | grep 1
      interval: 60s
      timeout: 60s
      retries: 6