name: CI/CD Pipeline

on:
  push:
    branches: ["feature/cicd"]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Creating .env file
        run: |
          mkdir -p .env
          echo "ENVIRONMENT=$ENVIRONMENT" > .env/test.env
          echo "APP_DATABASE_NAME=$APP_DATABASE_NAME" >> .env/test.env
          echo "DATABASE_URL=$DATABASE_URL" >> .env/test.env
          echo "SECRET_KEY=$SECRET_KEY" >> .env/test.env
          echo "ALGORITHM=$ALGORITHM" >> .env/test.env
          echo "DEFAULT_ADMIN_EMAIL=$DEFAULT_ADMIN_EMAIL" >> .env/test.env
          echo "DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD" >> .env/test.env
        shell: bash
        env:
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
          APP_DATABASE_NAME: ${{ env.APP_DATABASE_NAME }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}
          DEFAULT_ADMIN_EMAIL: ${{ secrets.DEFAULT_ADMIN_EMAIL }}
          DEFAULT_ADMIN_PASSWORD: ${{ secrets.DEFAULT_ADMIN_PASSWORD }}

      - name: "Run tests"
        run: chmod +x bin/linux/test.sh && ./bin/linux/test.sh

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME_DOCKER_HUB }}
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.IMAGE_TAG }}
